leftnav:
- identifier: ca41b018-7ff0-c8ed-4fc9-7698998b6d73
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 36beea6b-fe1e-356c-d9bf-7bb8f1ed5213
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 6799682c-87d0-db5f-8d54-ef1a5b78a61d
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: ceced5dd-a827-0c02-5d7f-c96ba1cd63dc
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 7f429711-5f35-219f-17be-16e6ace1b715
  name: Exams
  pageRef: /pages/exams
  weight: 50
